### ISSUE TITLE
The repo is missing "envs.h"

### ISSUE THREAD

**Issue by kgbvax** [kmizta/m5stack-co2-monitor#1]
Good day.
The repo is missing envs.h. Although I can see what is missing, the semantics need to be guessed so it would be very kind if you can add the missing file.
Best regards,
 i

**Comment by RobMBSos** [comment]
Hi, @kgbvax I have the same problem but wasn't able to resolve could you please guide me?
By the way, I have sent you an email, regards!

**Comment by kmizta** [comment]
Hi @RobMBSos sorry for inconvenience, in envs.h please define WIFI SSID and other constant values like below:
```
#define WIFI_SSID "YOUR SSID"
#define WIFI_PASSWORD "YOUR PASSWORD"
#define AMBIENT_CHID 11111
#define AMBIENT_WRITEKEY "YOUR WRITE KEY"
#define PB_APIKEY "YOUR PUSHBULLET API KEY"
```
please create envs.h and add it in project.
if you don't use wifi, ambient, or pushbullet, just don't write anything in envs.h and comment out USE_AMBIENT and USE_PUSHBULLET in co2monitor.ino.

I'm fixing this issue in the next version.

**Comment by RobMBSos** [comment]
> Hi @RobMBSos sorry for inconvenience, in envs.h please define WIFI SSID and other constant values like below:
> 
> ```
> #define WIFI_SSID "YOUR SSID"
> #define WIFI_PASSWORD "YOUR PASSWORD"
> #define AMBIENT_CHID 11111
> #define AMBIENT_WRITEKEY "YOUR WRITE KEY"
> #define PB_APIKEY "YOUR PUSHBULLET API KEY"
> ```
> 
> please create envs.h and add it in project.
> if you don't use wifi, ambient, or pushbullet, just don't write anything in envs.h and comment out USE_AMBIENT and USE_PUSHBULLET in co2monitor.ino.
> 
> I'm fixing this issue in the next version.

Dear @kmizta thank you for your help and response.
I tried to remove envs.h all ambient / push bullet and WIFI code but it seems M5Stack display will not initialize either give any error. I have tested other programs and the device works well.
